plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nocttech.sonystand'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nocttech.sonystand'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
